loansapp/urls.py
from django.urls import path
from . import views

app_name = "loansapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # loans management
    ## experiment with generic class based view
    path("add_loan", views.loan_add, name="loan_add"),
    path("loan_list", views.loan_list, name="loan_list"),
    path("loan_search", views.loan_search, name="loan_search"),
    path("loan_details/<int:loan_id>", views.loan_details, name="loan_details"),
    path("loan_details/<int:loan_id>/edit/", views.loan_details, {'edit': True}, name="loan_details_edit"),
    path("loan_update/<int:loan_id>", views.loan_update, name="loan_update"),

    path("add_payment/<int:loan_id>", views.loan_payment_add, name="loan_payment_add"),

    # vendors management
    path("vendors", views.vendor_list, name="vendor_list"),
    path("add_vendor", views.vendor_add, name="vendor_add"),
    path("vendor_details/<int:vendor_id>", views.vendor_details, name="vendor_details"),
    path("vendor_details/<int:vendor_id>/edit", views.vendor_details, {'edit': True}, name="vendor_details_edit"),
    path("vendor_update/<int:vendor_id>", views.vendor_update, name="vendor_update"),
]

myloans/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("loansapp.urls"),)
]

loansapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator, MinLengthValidator, MaxLengthValidator
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from decimal import Decimal
from utils import *

# Create your models here.
username_regex = RegexValidator(
    regex=r'^[0-9a-zA-Z_-]*$',
    message='Please use only supported chars'
)

class User(AbstractUser):
    # require min length 3 chars of the username
    AbstractUser._meta.get_field('username').validators = [MinLengthValidator(3), MaxLengthValidator(50)]
    AbstractUser._meta.get_field('username').validators = [username_regex]

    def __str__(self) -> str:
        return f"{self.username}"

class Statuses(models.IntegerChoices):
    UNPAID = 0, _("Unpaid")
    PAIDPARTLY = 1, _("Paid partly")
    PAID = 2, _("Paid")

class Loans(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="loans", editable=False)
    vendor = models.ForeignKey("Vendors", on_delete=models.PROTECT, related_name="loans")
    status = models.IntegerField(default=Statuses.UNPAID, choices=Statuses.choices)
    first_payment_date = models.DateField()
    last_payment_date = models.DateField()
    agreement_id = models.CharField(max_length=50)
    due_day = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(30)])
    amount_total = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    amount_outstanding = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    min_installment_amount = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    # last_edit = models.DateField(auto_now=True)

    def clean(self):
        # Custom validations for first/last_payment_date
        if self.first_payment_date and self.last_payment_date:
            if self.first_payment_date > self.last_payment_date:
                raise ValidationError({
                    'first_payment_date': 'First payment date has to be before last payment date.'
                })
            if self.first_payment_date.day != self.last_payment_date.day:
                raise ValidationError({
                    'last_payment_date': 'First & last payment dates have to be on the same day of the month.'
                })
        else:
            # Check if either date is None and raise a validation error accordingly
            if not self.first_payment_date:
                raise ValidationError({'first_payment_date': 'First payment date is required.'})
            if not self.last_payment_date:
                raise ValidationError({'last_payment_date': 'Last payment date is required.'})


class Vendors(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="vendors", editable=False)

    def __str__(self) -> str:
        return f"{self.name}"

class Installments(models.Model):
    loan = models.ForeignKey(Loans, on_delete=models.CASCADE, related_name="installments")
    amount = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    payment_date = models.DateField(null=True)
    payment_status = models.IntegerField(default=Statuses.UNPAID, choices=Statuses.choices)

class Payments(models.Model):
    loan = models.ForeignKey(Loans, on_delete=models.CASCADE, related_name="payments")
    amount = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    payment_date = models.DateField()

    def clean(self):
        super().clean()
        
        # Validate if there is a loan provided before running other custom validations
        if not self.loan:
            raise ValidationError('Loan must be set before validating.')

        # Ensure payment_date is provided before validation
        if not self.payment_date:
            raise ValidationError({'payment_date': 'Payment date is required.'})
    
        # Custom validations for payment_date not earlier than first_payment_date in the loan model
        min_allowed_date = date_add_months(self.loan.first_payment_date, 1, "substract")
        if self.payment_date < min_allowed_date:
            raise ValidationError({
                'payment_date': f'Payment date cannot be earlier than {min_allowed_date} (1 month before the first payment date of the loan).'
            })

loansapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.db import IntegrityError
from datetime import datetime, date
from utils import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic.list import ListView

from django.db.models import CharField, TextField, Sum, Count, Q
from django.db.models.functions import Lower

from .models import *
from .forms import *

# Create your views here.
def index(request):
    '''
    Generates dashboard view with statistical data about logged in user loans
    '''

    def period_stats(date_start=None, date_end=None):
        '''
        calculates installments stats for a given time period (months)
        '''
        # by default set the period to the next full month
        if date_start is None and date_end is None:
            period_date_start = date_add_months(date.today(), 1, day="first")
            period_date_end = date_add_months(date.today(), 1, day="last")
        elif (date_start is None and date_end is not None) or (date_start is not None and date_end is None):
            print('Error date_start or date_end is None')
        # else set the period to selected full months
        else:
            period_date_start = date_add_months(datetime.strptime(date_start, "%Y-%m-%d"), 0, day="first")
            period_date_end = date_add_months(datetime.strptime(date_end, "%Y-%m-%d"), 0, day="last")

        # caluclate installments stats for selected period
        myloans_selectedperiod_loans_count = Loans.objects.filter(user=request.user).filter(installments__payment_date__gte=period_date_start).filter(installments__payment_date__lte=period_date_end).distinct().count()
        myloans_selectedperiod_installments_paid_amount = Installments.objects.filter(loan__user=request.user).filter(payment_date__gte=period_date_start).filter(payment_date__lte=period_date_end).filter(payment_status=2).aggregate(Sum('amount'))
        myloans_selectedperiod_installments_paid_amount = myloans_selectedperiod_installments_paid_amount[next(iter(myloans_selectedperiod_installments_paid_amount))]
        if myloans_selectedperiod_installments_paid_amount is None:
            myloans_selectedperiod_installments_paid_amount = 0
        myloans_selectedperiod_installments_unpaid_amount = Installments.objects.filter(loan__user=request.user).filter(payment_date__gte=period_date_start).filter(payment_date__lte=period_date_end).filter(payment_status=0).aggregate(Sum('amount'))
        myloans_selectedperiod_installments_unpaid_amount = myloans_selectedperiod_installments_unpaid_amount[next(iter(myloans_selectedperiod_installments_unpaid_amount))]
        if myloans_selectedperiod_installments_unpaid_amount is None:
            myloans_selectedperiod_installments_unpaid_amount = 0

        return period_date_start, period_date_end, myloans_selectedperiod_loans_count, myloans_selectedperiod_installments_paid_amount, myloans_selectedperiod_installments_unpaid_amount

    # myloans stats
    myloans_paid_amount = Loans.objects.filter(user=request.user).filter(status=2).aggregate(Sum('amount_total'))
    myloans_paid_amount = myloans_paid_amount[next(iter(myloans_paid_amount))] or 0
    myloans_paid_amount = round(myloans_paid_amount, 2)
    myloans_paid_count = Loans.objects.filter(user=request.user).filter(status=2).count()
    myloans_paid_partly_amount = Loans.objects.filter(user=request.user).filter(status=1).aggregate(Sum('amount_total'))
    myloans_paid_partly_amount = myloans_paid_partly_amount[next(iter(myloans_paid_partly_amount))] or 0
    myloans_paid_partly_count = Loans.objects.filter(user=request.user).filter(status=1).count()
    myloans_unpaid_amount = Loans.objects.filter(user=request.user).filter(status=0).aggregate(Sum('amount_total'))
    myloans_unpaid_amount = myloans_unpaid_amount[next(iter(myloans_unpaid_amount))] or 0
    myloans_unpaid_amount = round(myloans_unpaid_amount, 2)
    myloans_unpaid_count = Loans.objects.filter(user=request.user).filter(status=0).count()
    myloans_amount = myloans_paid_partly_amount + myloans_paid_amount + myloans_unpaid_amount
    myloans_count = Loans.objects.filter(user=request.user).count()

    # current month stats
    myloans_currentmonth_name = datetime.today().strftime("%B")
    myloans_currentmonth_start, myloans_currentmonth_end, myloans_currentmonth_loans_count, myloans_currentmonth_installments_paid_amount, myloans_currentmonth_installments_unpaid_amount = period_stats(date_start=date.today().strftime("%Y-%m-%d"), date_end=date.today().strftime("%Y-%m-%d"))
    myloans_currentmonth_installments_paid_amount = round(myloans_currentmonth_installments_paid_amount, 2)
    myloans_currentmonth_installments_unpaid_amount = round(myloans_currentmonth_installments_unpaid_amount, 2)
    myloans_currentmonth_start = date_add_months(date.today(), 0, day="first")
    myloans_currentmonth_end = date_add_months(date.today(), 0, day="last")


    # Get parameters from request.GET
    date_from = request.GET.get('date_from', None)
    date_to = request.GET.get('date_to', None)

    # selected period (months) stats
    myloans_selectedperiod_start, myloans_selectedperiod_end, myloans_selectedperiod_loans_count, myloans_selectedperiod_installments_paid_amount, myloans_selectedperiod_installments_unpaid_amount  = period_stats(date_from, date_to)
    myloans_selectedperiod_installments_paid_amount = round(myloans_selectedperiod_installments_paid_amount, 2)
    myloans_selectedperiod_installments_unpaid_amount = round(myloans_selectedperiod_installments_unpaid_amount, 2)

    # Initialize date filter form
    if myloans_selectedperiod_start is not None and myloans_selectedperiod_end is not None:
        initial_data = {
            'date_from': myloans_selectedperiod_start.strftime("%Y-%m-%d"),
            'date_to': myloans_selectedperiod_end.strftime("%Y-%m-%d"),
        }
        print(initial_data['date_from'], type(initial_data['date_from']))
        print(initial_data['date_to'], type(initial_data['date_to']))

    form_filter_dates = LoanFilterDatesForm(initial=initial_data)
    if form_filter_dates.is_valid():
        date_from = myloans_selectedperiod_start
        date_to = myloans_selectedperiod_end

    context = {
        "myloans_amount": myloans_amount,
        "myloans_count": myloans_count,
        "myloans_paid_amount": myloans_paid_amount,
        "myloans_paid_count": myloans_paid_count,
        "myloans_paid_partly_amount": myloans_paid_partly_amount,
        "myloans_paid_partly_count": myloans_paid_partly_count,
        "myloans_unpaid_amount": myloans_unpaid_amount,
        "myloans_unpaid_count": myloans_unpaid_count,
        "myloans_currentmonth_start" : myloans_currentmonth_start,
        "myloans_currentmonth_end" : myloans_currentmonth_end,
        "myloans_currentmonth_name" : myloans_currentmonth_name,
        "myloans_currentmonth_loans_count": myloans_currentmonth_loans_count,
        "myloans_currentmonth_installments_paid_amount": myloans_currentmonth_installments_paid_amount,
        "myloans_currentmonth_installments_unpaid_amount": myloans_currentmonth_installments_unpaid_amount,
        "form_filter_dates" : form_filter_dates,
        "myloans_selectedperiod_start" : myloans_selectedperiod_start,
        "myloans_selectedperiod_end" : myloans_selectedperiod_end,
        "myloans_selectedperiod_loans_count":myloans_selectedperiod_loans_count,
        "myloans_selectedperiod_installments_paid_amount": myloans_selectedperiod_installments_paid_amount,
        "myloans_selectedperiod_installments_unpaid_amount": myloans_selectedperiod_installments_unpaid_amount,
    }

    return render(request, "index.html", context)


## Vendors management
def vendor_list(request):
    '''
    List all vendors
    '''
    vendors = Vendors.objects.filter(user=request.user).order_by(Lower("name")).annotate(
        loans_total=Count('loans'),
        loans_inprogress=Count('loans', filter=Q(loans__status=0) | Q(loans__status=1)),
        loans_closed=Count('loans', filter=Q(loans__status=2))
    )
    paginator = Paginator(vendors, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "vendor_list.html", {
        "page_obj": page_obj
    })


def vendor_add(request):
    '''
    Add new vendor (GET: render form, POST: add to DB)
    '''
    # check if method is POST
    if request.method == "POST":
        # take in the data submitted by the user and save it as a form
        form = NewVendorForm(request.POST)
        # check if form data is valid (server-side)
        if form.is_valid():
            # save vendor to DB
            # create new vendor object, but don't save to db yet
            new_vendor = form.save(commit=False)
            # set user field for the currently logged in user
            new_vendor.user = request.user
            # save update new_vendor to db
            new_vendor.save()
            # redirect user back to the vendors list view
            # TODO message that added successfuly
            # messages.add_message(request, messages.SUCCESS, "new vendor has been added") # propoer way of adding a message without a shortcut
            messages.success(request, "New Vendor has been added.")
            return HttpResponseRedirect(reverse("loansapp:vendor_list"))
        else:
            # store form errors in session so form rendered in other view functions will also get them
            request.session['vendor_form_data'] = request.POST
            request.session['vendor_form_errors'] = form.errors
            messages.error(request, "There were errors in the add vendor form.")
            return HttpResponseRedirect(reverse("loansapp:vendor_add"))

loansapp/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}My Loans{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- tailwind css & inter font family -->
    <link href="{% static 'css/output.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />

    <!-- Alpine.js framework-->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"
    ></script>
  </head>
  <body>
    <style>
      [x-cloak] {
        display: none !important;
      }
    </style>
    <nav class="bg-gray-800" x-data="{ open: false, dropdown_open: false }">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 justify-between">
          <div class="flex">
            <div class="-ml-2 mr-2 flex items-center md:hidden">
              <!-- Mobile menu button -->
              <button
                @click="open = ! open"
                type="button"
                class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                aria-controls="mobile-menu"
                aria-expanded="false"
              >
                <span class="absolute -inset-0.5"></span>
                <span class="sr-only">Open main menu</span>
                <!--
                    Icon when menu is closed.
                    Menu open: "hidden", Menu closed: "block"
                -->
                <svg
                  class="h-6 w-6"
                  x-bind:class="open ? 'hidden' : 'block'"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  aria-hidden="true"
                  data-slot="icon"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                  />
                </svg>
                <!--
                    Icon when menu is open.
                    Menu open: "block", Menu closed: "hidden"
                -->
                <svg
                  class="h-6 w-6"
                  x-cloak
                  x-bind:class="open ? 'block' : 'hidden'"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  aria-hidden="true"
                  data-slot="icon"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M6 18 18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>
            <div class="flex flex-shrink-0 items-center">
              <img
                class="h-8 w-auto"
                src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500"
                alt="Your Company"
              />
            </div>
            {% if user.is_authenticated %}
            <!-- main nav options -->
            <div class="hidden md:ml-6 md:flex md:items-center md:space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <a
                href="{% url 'loansapp:index' %}"
                :class="{'bg-gray-900 text-white': window.location.pathname === '{% url 'loansapp:index' %}', 'text-gray-300 hover:bg-gray-700 hover:text-white': window.location.pathname !== '{% url 'loansapp:index' %}'}"
                class="rounded-md px-3 py-2 text-sm font-medium"
                aria-current="page"
                >Dashboard</a
              >
              <a
                href="{% url 'loansapp:loan_list' %}"
                :class="{'bg-gray-900 text-white': window.location.pathname === '{% url 'loansapp:loan_list' %}', 'text-gray-300 hover:bg-gray-700 hover:text-white': window.location.pathname !== '{% url 'loansapp:loan_list' %}'}"
                class="rounded-md px-3 py-2 text-sm font-medium"
                >Loans</a
              >
              <a
                href="{% url 'loansapp:vendor_list' %}"
                :class="{'bg-gray-900 text-white': window.location.pathname === '{% url 'loansapp:vendor_list' %}', 'text-gray-300 hover:bg-gray-700 hover:text-white': window.location.pathname !== '{% url 'loansapp:vendor_list' %}'}"
                class="rounded-md px-3 py-2 text-sm font-medium"
                >Vendors</a
              >
            </div>
          </div>
          <!-- login mngmt -->
          <div class="flex items-center">
            <span class="text-white px-3.5"
              >Hi <strong>{{ user.username }} </strong></span
            >
            <form action="{% url 'loansapp:logout' %}">
              <button
                type="submit"
                class="relative inline-flex items-center gap-x-2 rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                <svg
                  class="h-5 w-5"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                  aria-hidden="true"
                  data-slot="icon"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M10 2a.75.75 0 0 1 .75.75v7.5a.75.75 0 0 1-1.5 0v-7.5A.75.75 0 0 1 10 2ZM5.404 4.343a.75.75 0 0 1 0 1.06 6.5 6.5 0 1 0 9.192 0 .75.75 0 1 1 1.06-1.06 8 8 0 1 1-11.313 0 .75.75 0 0 1 1.06 0Z"
                  />
                </svg>
                Sign Out
              </button>
            </form>
          </div>
          {% else %} {% endif %}
        </div>
      </div>

      <!-- Mobile menu, show/hide based on menu state. -->
      <div x-cloak x-show="open" class="md:hidden" id="mobile-menu">
        <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
          <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
          <a
            href="{% url 'loansapp:index' %}"
            :class="{'bg-gray-900 text-white': window.location.pathname === '{% url 'loansapp:index' %}', 'text-gray-300 hover:bg-gray-700 hover:text-white': window.location.pathname !== '{% url 'loansapp:index' %}'}"
            class="block rounded-md px-3 py-2 text-base font-medium"
            aria-current="page"
            >Dashboard</a
          >
          <a
            href="{% url 'loansapp:loan_list' %}"
            :class="{'bg-gray-900 text-white': window.location.pathname === '{% url 'loansapp:loan_list' %}', 'text-gray-300 hover:bg-gray-700 hover:text-white': window.location.pathname !== '{% url 'loansapp:loan_list' %}'}"
            class="block rounded-md px-3 py-2 text-base font-medium"
            >Loans</a
          >
          <a
            href="{% url 'loansapp:vendor_list' %}"
            :class="{'bg-gray-900 text-white': window.location.pathname === '{% url 'loansapp:vendor_list' %}', 'text-gray-300 hover:bg-gray-700 hover:text-white': window.location.pathname !== '{% url 'loansapp:vendor_list' %}'}"
            class="block rounded-md px-3 py-2 text-base font-medium"
            >Vendors</a
          >
        </div>
      </div>
    </nav>

    {% include 'includes/messages.html' %}

    <div class="container px-4 sm:px-6 lg:px-8">
      {% block body %} {% endblock %}
    </div>
  </body>
</html>

loansapp/templates/login.html
{% extends "layout.html" %}

{% block body %}
<div class="canvas">

    {% include 'includes/header_page.html' with title="Login" %}

    <form action="{% url 'loansapp:login' %}" method="post" class="max-w-md mx-auto">
        {% csrf_token %}
        <div class="space-y-12">
            <div class="border-b border-gray-900/10 pb-12">

                    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                        <!-- username input -->
                        <div class="sm:col-span-4">
                            <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                            <div class="mt-2">
                                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                    <input type="text" name="username" id="username" autocomplete="username" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Enter username">
                                </div>
                            </div>
                        </div>
                        <!-- password input -->
                        <div class="sm:col-span-4">
                            <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                            <div class="mt-2">
                                <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                    <input type="password" name="password" id="password" autocomplete="password" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Enter password">
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>

        <div class="mt-6 flex flex-wrap items-center justify-end gap-x-6">
            <button type="submit" class="block w-full sm:w-auto rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Login</button>
            <p class="w-full sm:w-auto">Don't have an account? <a class="text-indigo-600" href="{% url 'loansapp:register' %}">Register here.</a></p>
        </div>
        

    </form>

</div>
{% endblock %}

loansapp/templates/register.html
{% extends "layout.html" %}

{% block body %}
<div>
    {% include 'includes/header_page.html' with title="Register" %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div>
        <form action="{% url 'loansapp:register' %}" method="post">
            {% csrf_token %}
            <div>
                <input class="" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div>
                <input class="" type="email" name="email" placeholder="Email Address">
            </div>
            <div>
                <input class="" type="password" name="password" placeholder="Password">
            </div>
            <div>
                <input class="" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="" type="submit" value="Register">
        </form>

        Already have an account? <a href="{% url 'loansapp:login' %}">Log In here.</a>
    </div>

</div>
{% endblock %}

loansapp/templates/vendor_details.html
{% extends "layout.html" %}

{% block body %}

    {% include 'includes/header_page.html' with title="Edit Vendor "|add:vendor.name %}
        <!-- Add Vendor Form -->
        <form method="post" action="{% url 'loansapp:vendor_update' vendor.id %}" class="sm:flex sm:flex-wrap items-end space-x-4">
            {% csrf_token %}

            <!-- Display any non-field errors -->
            {% if form_vendor_edit.non_field_errors %}
                <div class="text-red-600 text-sm">
                    <!-- Non-field Errors -->
                    {{ form_vendor_edit.non_field_errors }}
                </div>
            {% endif %}
    
            <!-- Name Field -->
            <div class="mt-2">
                <!-- Label -->
                <label for="{{ form_vendor_edit.name.id_for_label }}" class="block text-sm/6 font-medium text-gray-900">
                    {{ form_vendor_edit.name.label }}
                    </label>

                <!-- Input Field Wrapper -->
                <div class="mt-2">
                    <input type="text" name="{{ form_vendor_edit.name.name }}" id="{{ form_vendor_edit.name.id_for_label }}" 
                        placeholder="{{ form_vendor_edit.name.field.widget.attrs.placeholder }}"
                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6"
                        value="{{ form_vendor_edit.name.value|default:'' }}"
                    >
                </div>
                {% if form_vendor_edit.name.errors %}
                    <div class="text-red-600 text-sm mt-1">
                        {% for error in form_vendor_edit.name.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- Submit Button -->
            <div class="mt-6 md:mt-0">
                <button type="submit" onclick="this.disabled=true; this.form.submit();" class="rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Update Vendor</button>
                <a class="text-sm/6 font-semibold text-gray-900" href="{% url 'loansapp:vendor_list' %}">Cancel</a>
            </div>
        </form>
{% endblock %}