loansapp/urls.py
from django.urls import path
from . import views

app_name = "loansapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    # loans management
    ## experiment with generic class based view
    path("add_loan", views.loan_add, name="loan_add"),
    path("loan_list", views.loan_list, name="loan_list"),
    path("loan_search", views.loan_search, name="loan_search"),
    path("loan_details/<int:loan_id>", views.loan_details, name="loan_details"),
    path("loan_details/<int:loan_id>/edit/", views.loan_details, {'edit': True}, name="loan_details_edit"),
    path("loan_update/<int:loan_id>", views.loan_update, name="loan_update"),

    path("add_payment/<int:loan_id>", views.loan_payment_add, name="loan_payment_add"),

    # vendors management
    path("vendors", views.vendor_list, name="vendor_list"),
    path("add_vendor", views.vendor_add, name="vendor_add"),
    path("vendor_details/<int:vendor_id>", views.vendor_details, name="vendor_details"),
    path("vendor_details/<int:vendor_id>/edit", views.vendor_details, {'edit': True}, name="vendor_details_edit"),
    path("vendor_update/<int:vendor_id>", views.vendor_update, name="vendor_update"),
]

myloans/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("loansapp.urls"),)
]

loansapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator, MinLengthValidator, MaxLengthValidator
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from decimal import Decimal
from utils import *

# Create your models here.
username_regex = RegexValidator(
    regex=r'^[0-9a-zA-Z_-]*$',
    message='Please use only supported chars'
)

class User(AbstractUser):
    # require min length 3 chars of the username
    AbstractUser._meta.get_field('username').validators = [MinLengthValidator(3), MaxLengthValidator(50)]
    AbstractUser._meta.get_field('username').validators = [username_regex]

    def __str__(self) -> str:
        return f"{self.username}"

class Statuses(models.IntegerChoices):
    UNPAID = 0, _("Unpaid")
    PAIDPARTLY = 1, _("Paid partly")
    PAID = 2, _("Paid")

class Loans(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="loans", editable=False)
    vendor = models.ForeignKey("Vendors", on_delete=models.PROTECT, related_name="loans")
    status = models.IntegerField(default=Statuses.UNPAID, choices=Statuses.choices)
    first_payment_date = models.DateField()
    last_payment_date = models.DateField()
    agreement_id = models.CharField(max_length=50)
    due_day = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(30)])
    amount_total = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    amount_outstanding = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    min_installment_amount = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    # last_edit = models.DateField(auto_now=True)

    def clean(self):
        # Custom validations for first/last_payment_date
        if self.first_payment_date and self.last_payment_date:
            if self.first_payment_date > self.last_payment_date:
                raise ValidationError({
                    'first_payment_date': 'First payment date has to be before last payment date.'
                })
            if self.first_payment_date.day != self.last_payment_date.day:
                raise ValidationError({
                    'last_payment_date': 'First & last payment dates have to be on the same day of the month.'
                })
        else:
            # Check if either date is None and raise a validation error accordingly
            if not self.first_payment_date:
                raise ValidationError({'first_payment_date': 'First payment date is required.'})
            if not self.last_payment_date:
                raise ValidationError({'last_payment_date': 'Last payment date is required.'})


class Vendors(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="vendors", editable=False)

    def __str__(self) -> str:
        return f"{self.name}"

class Installments(models.Model):
    loan = models.ForeignKey(Loans, on_delete=models.CASCADE, related_name="installments")
    amount = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    payment_date = models.DateField(null=True)
    payment_status = models.IntegerField(default=Statuses.UNPAID, choices=Statuses.choices)

class Payments(models.Model):
    loan = models.ForeignKey(Loans, on_delete=models.CASCADE, related_name="payments")
    amount = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    payment_date = models.DateField()

    def clean(self):
        super().clean()
        
        # Validate if there is a loan provided before running other custom validations
        if not self.loan:
            raise ValidationError('Loan must be set before validating.')

        # Ensure payment_date is provided before validation
        if not self.payment_date:
            raise ValidationError({'payment_date': 'Payment date is required.'})
    
        # Custom validations for payment_date not earlier than first_payment_date in the loan model
        min_allowed_date = date_add_months(self.loan.first_payment_date, 1, "substract")
        if self.payment_date < min_allowed_date:
            raise ValidationError({
                'payment_date': f'Payment date cannot be earlier than {min_allowed_date} (1 month before the first payment date of the loan).'
            })

loansapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.db import IntegrityError
from datetime import datetime, date
from utils import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic.list import ListView

from django.db.models import CharField, TextField, Sum, Count, Q
from django.db.models.functions import Lower

from .models import *
from .forms import *

# Create your views here.
def index(request):
    '''
    Generates dashboard view with statistical data about logged in user loans
    '''

    def period_stats(date_start=None, date_end=None):
        '''
        calculates installments stats for a given time period (months)
        '''
        # by default set the period to the next full month
        if date_start is None and date_end is None:
            period_date_start = date_add_months(date.today(), 1, day="first")
            period_date_end = date_add_months(date.today(), 1, day="last")
        elif (date_start is None and date_end is not None) or (date_start is not None and date_end is None):
            print('Error date_start or date_end is None')
        # else set the period to selected full months
        else:
            period_date_start = date_add_months(datetime.strptime(date_start, "%Y-%m-%d"), 0, day="first")
            period_date_end = date_add_months(datetime.strptime(date_end, "%Y-%m-%d"), 0, day="last")

        # caluclate installments stats for selected period
        myloans_selectedperiod_loans_count = Loans.objects.filter(user=request.user).filter(installments__payment_date__gte=period_date_start).filter(installments__payment_date__lte=period_date_end).distinct().count()
        myloans_selectedperiod_installments_paid_amount = Installments.objects.filter(loan__user=request.user).filter(payment_date__gte=period_date_start).filter(payment_date__lte=period_date_end).filter(payment_status=2).aggregate(Sum('amount'))
        myloans_selectedperiod_installments_paid_amount = myloans_selectedperiod_installments_paid_amount[next(iter(myloans_selectedperiod_installments_paid_amount))]
        if myloans_selectedperiod_installments_paid_amount is None:
            myloans_selectedperiod_installments_paid_amount = 0
        myloans_selectedperiod_installments_unpaid_amount = Installments.objects.filter(loan__user=request.user).filter(payment_date__gte=period_date_start).filter(payment_date__lte=period_date_end).filter(payment_status=0).aggregate(Sum('amount'))
        myloans_selectedperiod_installments_unpaid_amount = myloans_selectedperiod_installments_unpaid_amount[next(iter(myloans_selectedperiod_installments_unpaid_amount))]
        if myloans_selectedperiod_installments_unpaid_amount is None:
            myloans_selectedperiod_installments_unpaid_amount = 0

        return period_date_start, period_date_end, myloans_selectedperiod_loans_count, myloans_selectedperiod_installments_paid_amount, myloans_selectedperiod_installments_unpaid_amount

    # myloans stats
    myloans_paid_amount = Loans.objects.filter(user=request.user).filter(status=2).aggregate(Sum('amount_total'))
    myloans_paid_amount = myloans_paid_amount[next(iter(myloans_paid_amount))] or 0
    myloans_paid_amount = round(myloans_paid_amount, 2)
    myloans_paid_count = Loans.objects.filter(user=request.user).filter(status=2).count()
    myloans_paid_partly_amount = Loans.objects.filter(user=request.user).filter(status=1).aggregate(Sum('amount_total'))
    myloans_paid_partly_amount = myloans_paid_partly_amount[next(iter(myloans_paid_partly_amount))] or 0
    myloans_paid_partly_count = Loans.objects.filter(user=request.user).filter(status=1).count()
    myloans_unpaid_amount = Loans.objects.filter(user=request.user).filter(status=0).aggregate(Sum('amount_total'))
    myloans_unpaid_amount = myloans_unpaid_amount[next(iter(myloans_unpaid_amount))] or 0
    myloans_unpaid_amount = round(myloans_unpaid_amount, 2)
    myloans_unpaid_count = Loans.objects.filter(user=request.user).filter(status=0).count()
    myloans_amount = myloans_paid_partly_amount + myloans_paid_amount + myloans_unpaid_amount
    myloans_count = Loans.objects.filter(user=request.user).count()

    # current month stats
    myloans_currentmonth_name = datetime.today().strftime("%B")
    myloans_currentmonth_start, myloans_currentmonth_end, myloans_currentmonth_loans_count, myloans_currentmonth_installments_paid_amount, myloans_currentmonth_installments_unpaid_amount = period_stats(date_start=date.today().strftime("%Y-%m-%d"), date_end=date.today().strftime("%Y-%m-%d"))
    myloans_currentmonth_installments_paid_amount = round(myloans_currentmonth_installments_paid_amount, 2)
    myloans_currentmonth_installments_unpaid_amount = round(myloans_currentmonth_installments_unpaid_amount, 2)
    myloans_currentmonth_start = date_add_months(date.today(), 0, day="first")
    myloans_currentmonth_end = date_add_months(date.today(), 0, day="last")


    # Get parameters from request.GET
    date_from = request.GET.get('date_from', None)
    date_to = request.GET.get('date_to', None)

    # selected period (months) stats
    myloans_selectedperiod_start, myloans_selectedperiod_end, myloans_selectedperiod_loans_count, myloans_selectedperiod_installments_paid_amount, myloans_selectedperiod_installments_unpaid_amount  = period_stats(date_from, date_to)
    myloans_selectedperiod_installments_paid_amount = round(myloans_selectedperiod_installments_paid_amount, 2)
    myloans_selectedperiod_installments_unpaid_amount = round(myloans_selectedperiod_installments_unpaid_amount, 2)

    # Initialize date filter form
    if myloans_selectedperiod_start is not None and myloans_selectedperiod_end is not None:
        initial_data = {
            'date_from': myloans_selectedperiod_start.strftime("%Y-%m-%d"),
            'date_to': myloans_selectedperiod_end.strftime("%Y-%m-%d"),
        }
        print(initial_data['date_from'], type(initial_data['date_from']))
        print(initial_data['date_to'], type(initial_data['date_to']))

    form_filter_dates = LoanFilterDatesForm(initial=initial_data)
    if form_filter_dates.is_valid():
        date_from = myloans_selectedperiod_start
        date_to = myloans_selectedperiod_end

    context = {
        "myloans_amount": myloans_amount,
        "myloans_count": myloans_count,
        "myloans_paid_amount": myloans_paid_amount,
        "myloans_paid_count": myloans_paid_count,
        "myloans_paid_partly_amount": myloans_paid_partly_amount,
        "myloans_paid_partly_count": myloans_paid_partly_count,
        "myloans_unpaid_amount": myloans_unpaid_amount,
        "myloans_unpaid_count": myloans_unpaid_count,
        "myloans_currentmonth_start" : myloans_currentmonth_start,
        "myloans_currentmonth_end" : myloans_currentmonth_end,
        "myloans_currentmonth_name" : myloans_currentmonth_name,
        "myloans_currentmonth_loans_count": myloans_currentmonth_loans_count,
        "myloans_currentmonth_installments_paid_amount": myloans_currentmonth_installments_paid_amount,
        "myloans_currentmonth_installments_unpaid_amount": myloans_currentmonth_installments_unpaid_amount,
        "form_filter_dates" : form_filter_dates,
        "myloans_selectedperiod_start" : myloans_selectedperiod_start,
        "myloans_selectedperiod_end" : myloans_selectedperiod_end,
        "myloans_selectedperiod_loans_count":myloans_selectedperiod_loans_count,
        "myloans_selectedperiod_installments_paid_amount": myloans_selectedperiod_installments_paid_amount,
        "myloans_selectedperiod_installments_unpaid_amount": myloans_selectedperiod_installments_unpaid_amount,
    }

    return render(request, "index.html", context)


## Vendors management
def vendor_list(request):
    '''
    List all vendors
    '''
    vendors = Vendors.objects.filter(user=request.user).order_by(Lower("name")).annotate(
        loans_total=Count('loans'),
        loans_inprogress=Count('loans', filter=Q(loans__status=0) | Q(loans__status=1)),
        loans_closed=Count('loans', filter=Q(loans__status=2))
    )
    paginator = Paginator(vendors, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "vendor_list.html", {
        "page_obj": page_obj
    })


def vendor_add(request):
    '''
    Add new vendor (GET: render form, POST: add to DB)
    '''
    # check if method is POST
    if request.method == "POST":
        # take in the data submitted by the user and save it as a form
        form = NewVendorForm(request.POST)
        # check if form data is valid (server-side)
        if form.is_valid():
            # save vendor to DB
            # create new vendor object, but don't save to db yet
            new_vendor = form.save(commit=False)
            # set user field for the currently logged in user
            new_vendor.user = request.user
            # save update new_vendor to db
            new_vendor.save()
            # redirect user back to the vendors list view
            # TODO message that added successfuly
            # messages.add_message(request, messages.SUCCESS, "new vendor has been added") # propoer way of adding a message without a shortcut
            messages.success(request, "New Vendor has been added.")
            return HttpResponseRedirect(reverse("loansapp:vendor_list"))
        else:
            # store form errors in session so form rendered in other view functions will also get them
            request.session['vendor_form_data'] = request.POST
            request.session['vendor_form_errors'] = form.errors
            messages.error(request, "There were errors in the add vendor form.")
            return HttpResponseRedirect(reverse("loansapp:vendor_add"))

loansapp/templates/includes/filter_dates.html
<!-- Date Filter Form -->
<form method="get" action="" class="flex flex-wrap items-end space-x-0 sm:space-x-4">

    <!-- Display any non-field errors -->
    {% if form_filter_dates.non_field_errors %}
        <div class="text-red-600 text-sm">
            <!-- Non-field Errors -->
            {{ form_filter_dates.non_field_errors }}
        </div>
    {% endif %}

    <!-- From Date Field -->
    <div class="w-full sm:w-auto">
        <!-- Label -->
        <label for="{{ form_filter_dates.date_from.id_for_label }}" class="block text-sm/6 font-medium text-gray-900">
            <!-- Search Query Label -->
            {{ form_filter_dates.date_from.label }}
            </label>
    
            <!-- Input Field Wrapper -->
            <div class="mt-2">
                <input type="date" name="{{ form_filter_dates.date_from.name }}" id="{{ form_filter_dates.date_from.id_for_label }}" 
                       placeholder="{{ form_filter_dates.date_from.field.widget.attrs.placeholder }}"
                       value="{{ form_filter_dates.date_from.value|date:'Y-m-d'|default:form_filter_dates.date_from.value }}"
                       class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
            </div>
    </div>

    <!-- To Date Field -->
    <div class="w-full mt-4 sm:mt-0 sm:w-auto">
        <!-- Label -->
        <label for="{{ form_filter_dates.date_to.id_for_label }}" class="block text-sm/6 font-medium text-gray-900">
            <!-- Search Query Label -->
            {{ form_filter_dates.date_to.label }}
            </label>
    
            <!-- Input Field Wrapper -->
            <div class="mt-2">
                <input type="date" name="{{ form_filter_dates.date_to.name }}" id="{{ form_filter_dates.date_to.id_for_label }}" 
                       placeholder="{{ form_filter_dates.date_to.field.widget.attrs.placeholder }}"
                       value="{{ form_filter_dates.date_to.value|date:'Y-m-d'|default:form_filter_dates.date_to.value }}"
                       class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
            </div>
    </div>

    <!-- Submit Button -->
    <div class="w-full mt-4 sm:mt-0 sm:w-auto">
        <button type="submit" class="block w-full rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Filter</button>
    </div>
</form>

loansapp/templates/includes/header_page.html
<h1 class="my-4 text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">{{ title }}</h1>

loansapp/templates/includes/messages.html
<!-- Global notification live region, needs to be rendered permanently at the end of the document -->
<div
  aria-live="assertive"
  class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:pt-20 sm: pb-6 sm:px-6"
  x-data="{ open: {% if messages %} true {% else %} false {% endif %} }"
  x-init="setTimeout(() => open = false, 3000)"
>
  <div
    x-show="open"
    x-cloak
    x-transition:enter="transform ease-out duration-300 transition"
    x-transition:enter-start="translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
    x-transition:enter-end="translate-y-0 opacity-100 sm:translate-x-0"
    x-transition:leave="transition ease-in duration-100"
    x-transition:leave-start="opacity-100"
    x-transition:leave-end="opacity-0"
    class="flex w-full flex-col items-center space-y-4 sm:items-end"
  >
    <!--
  Notification panel, dynamically insert this into the live region when it needs to be displayed

  Entering: "transform ease-out duration-300 transition"
    From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
    To: "translate-y-0 opacity-100 sm:translate-x-0"
  Leaving: "transition ease-in duration-100"
    From: "opacity-100"
    To: "opacity-0"
-->
    {% if messages %} {% for message in messages %}
    <div
      class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black/5"
    >
      <div class="p-4">
        <div class="flex items-start">
          <div class="shrink-0">
            {% if message.tags == "success" %}
            <svg
              class="size-6 text-green-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              aria-hidden="true"
              data-slot="icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
              />
            </svg>
            {% elif message.tags == "error" %}
            <svg
              class="size-6 text-red-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              aria-hidden="true"
              data-slot="icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"
              />
            </svg>
            {% else %}
            <svg
              class="size-6 text-gray-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z"
              />
            </svg>
            {% endif %}
          </div>
          <div class="ml-3 w-0 flex-1 pt-0.5">
            <p class="text-sm font-medium text-gray-900">
              {{ message.tags|capfirst }}
            </p>
            <p class="mt-1 text-sm text-gray-500">{{ message }}</p>
          </div>
          <div class="ml-4 flex shrink-0">
            <button
              @click="open = ! open"
              type="button"
              class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
            >
              <span class="sr-only">Close</span>
              <svg
                class="size-5"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
                data-slot="icon"
              >
                <path
                  d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %} {% endif %}
  </div>
</div>

loansapp/templates/includes/search_simple.html
<!-- Simple Search Form -->
<form action="{% url 'loansapp:loan_search' %}" method="post" class="flex flex-wrap justify-left items-end space-x-0 sm:space-x-4">
    {% csrf_token %}

    <!-- Display any non-field errors -->
    {% if form_search.non_field_errors %}
        <div class="text-red-600 text-sm">
            <!-- Non-field Errors -->
            {{ form_search.non_field_errors }}
        </div>
    {% endif %}

    <!-- Search Query Field -->
    <div class="w-full sm:w-auto">
        <!-- Label -->
        <label for="{{ form_search.search_query.id_for_label }}" class="block text-sm/6 font-medium text-gray-900">
            <!-- Search Query Label -->
            {{ form_search.search_query.label }}
        </label>

        <!-- Input Field Wrapper -->
        <div class="mt-2">
            <input type="text" name="{{ form_search.search_query.name }}" id="{{ form_search.search_query.id_for_label }}" 
                   placeholder="{{ form_search.search_query.field.widget.attrs.placeholder }}"
                   class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
        </div>

        <!-- Display field-specific errors -->
        {% if form_search.search_query.errors %}
            <div class="text-red-600 text-sm">
                <!-- Search Query Errors -->
                {{ form_search.search_query.errors }}
            </div>
        {% endif %}
    </div>

    <!-- Submit Button -->
    <div class="w-full mt-4 sm:mt-0 sm:w-auto">
        <input type="submit" value="Search" 
               class="block w-full rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
    </div>
</form>